
development:
  adapter: mysql2
  encoding: utf8
  database: aunderdown
  pool: 5
  username: aunderdown
  password: csc342
  host: cs.furman.edu
  port: 3306


test:
  adapter: mysql2
  encoding: utf8
  database: aunderdown
  pool: 5
  username: aunderdown
  password: csc342
  host: cs.furman.edu
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: aunderdown
  pool: 5
  username: aunderdown
  password: csc342
  host: cs.furman.edu
  port: 3306
